package com.wlg.db.wlg_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE DevicesBaseDto PLEASE EDIT ../DevicesDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Devices object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.wlg.db.wlg_db.entity.Devices;
// Import relations
import com.wlg.db.wlg_db.dtos.infos.GPSInfo;

import com.wlg.db.wlg_db.dtos.infos.SimInfo;




public class DevicesBaseDto {
	
	private Long _id;
	
	// Attributes
	
	// Relations _gps
	private Long _gps;
	
	// Relations _sim
	private Long _sim;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
    
	public void set_gps(GPSInfo _gps) {
		this._gps = _gps.get_id();
	}

	public Long get_gps() {
		return _gps;
	}
	
	public void set_sim(SimInfo _sim) {
		this._sim = _sim.get_id();
	}

	public Long get_sim() {
		return _sim;
	}
	

    
}