package com.wlg.db.wlg_db.dtos.infos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE GPSInfoDto PLEASE EDIT ../GPSInfo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the info of GPS object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;


public class GPSBaseInfo {
	
	private Long _id;
	// Attributes
    private Double Imei;
    private String Models;
    private Double SN;
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Double getImei() {
		return Imei;
	}

	public void setImei(Double Imei) {
		this.Imei = Imei;
	}
	public String getModels() {
		return Models;
	}

	public void setModels(String Models) {
		this.Models = Models;
	}
	public Double getSN() {
		return SN;
	}

	public void setSN(Double SN) {
		this.SN = SN;
	}
}