package com.wlg.db.wlg_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE GPSBase PLEASE EDIT ../GPS.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of GPS object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.wlg.db.wlg_db.entity.GPS;
// Import relations
import com.wlg.db.wlg_db.entity.Devices;




@MappedSuperclass
public class GPSBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column(nullable=false)
    private Double Imei;
	@Column()
    private String Models;
	@Column(nullable=false)
    private Double SN;
	
	// Relations Devices
	@OneToMany(mappedBy="_gps")
	private List<Devices> _gps_Devices = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Double getImei() {
		return Imei;
	}

	public void setImei(Double Imei) {
		this.Imei = Imei;
	}
	public String getModels() {
		return Models;
	}

	public void setModels(String Models) {
		this.Models = Models;
	}
	public Double getSN() {
		return SN;
	}

	public void setSN(Double SN) {
		this.SN = SN;
	}
    
	// Relations Devices
	
	public List<Devices> getDevices() {
		return this._gps_Devices;
	}

	public void addDevices(Devices Devices) {
		this._gps_Devices.add(Devices);
	}

	public void removeDevices(Devices Devices) {
		this._gps_Devices.remove(Devices);
	}
	

    
}