package com.wlg.db.wlg_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE SimBase PLEASE EDIT ../Sim.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Sim object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.wlg.db.wlg_db.entity.Sim;
// Import relations
import com.wlg.db.wlg_db.entity.Devices;




@MappedSuperclass
public class SimBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column(nullable=false)
    private Double SimNo;
	
	// Relations Devices
	@OneToMany(mappedBy="_sim")
	private List<Devices> _sim_Devices = new ArrayList<>();
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Double getSimNo() {
		return SimNo;
	}

	public void setSimNo(Double SimNo) {
		this.SimNo = SimNo;
	}
    
	// Relations Devices
	
	public List<Devices> getDevices() {
		return this._sim_Devices;
	}

	public void addDevices(Devices Devices) {
		this._sim_Devices.add(Devices);
	}

	public void removeDevices(Devices Devices) {
		this._sim_Devices.remove(Devices);
	}
	

    
}