
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DEVICES
export const CREATE_DEVICES_SUCCESS = "CREATE_DEVICES_SUCCESS";
export const DELETE_DEVICES_SUCCESS = "DELETE_DEVICES_SUCCESS";
export const FINDBY_GPS_DEVICES_SUCCESS = "FINDBY_GPS_DEVICES_SUCCESS";
export const FINDBY_SIM_DEVICES_SUCCESS = "FINDBY_SIM_DEVICES_SUCCESS";
export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS";
export const LIST_DEVICES_SUCCESS = "LIST_DEVICES_SUCCESS";
export const UPDATE_DEVICES_SUCCESS = "UPDATE_DEVICES_SUCCESS";

// GPS
export const CREATE_GPS_SUCCESS = "CREATE_GPS_SUCCESS";
export const DELETE_GPS_SUCCESS = "DELETE_GPS_SUCCESS";
export const GET_GPS_SUCCESS = "GET_GPS_SUCCESS";
export const LIST_GPS_SUCCESS = "LIST_GPS_SUCCESS";
export const UPDATE_GPS_SUCCESS = "UPDATE_GPS_SUCCESS";

// SIM
export const CREATE_SIM_SUCCESS = "CREATE_SIM_SUCCESS";
export const DELETE_SIM_SUCCESS = "DELETE_SIM_SUCCESS";
export const GET_SIM_SUCCESS = "GET_SIM_SUCCESS";
export const LIST_SIM_SUCCESS = "LIST_SIM_SUCCESS";
export const UPDATE_SIM_SUCCESS = "UPDATE_SIM_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
